### ISSUE TITLE
div not closed in Template "mod_faqpage_accordion.html5"

### ISSUE THREAD

**Issue by con2net** [w3scout/contao-searchfaq-bundle#1]
In template file "mod_faqpage_accordion.html5", Line 12, the second div element is not closed. The result is a nested display of the accordions. I think it is not necessary? I removed it and it works fine.
Regards

**Comment by w3scout** [comment]
Fixed in #e0f5f54

**Comment by w3scout** [comment]
Fixed in #https://github.com/w3scout/contao-searchfaq-bundle/commit/e0f5f549fa3d2b412ba7f959b9ee9ae7071bc786
